name: httplogger
description: Convenient way to store and present `http` client responses.
version: 0.0.1
author: Azamat Murzagalin
homepage: https://github.com/azamat-murzagalin/httplogger

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ">=0.12.0 <1.0.0"
  shared_preferences: ">=0.5.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
